thormang3:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125  
  
  # Position Controllers ---------------------------------------
  
  # Body ------

  torso_y_position:
    type: effort_controllers/JointPositionController
    joint: torso_y
    pid: {p: 10000.0, i: 0.1, d: 900.0}

  # Left Arm -----

  l_arm_sh_p1_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_sh_p1
    pid: {p: 15000.0, i: 0.1, d: 1000.0}

  l_arm_sh_r_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_sh_r
    pid: {p: 15000.0, i: 0.1, d: 800.0}

  l_arm_sh_p2_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_sh_p2
    pid: {p: 15000.0, i: 0.1, d: 800.0}

  l_arm_el_y_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_el_y
    pid: {p: 15000.0, i: 0.1, d: 800.0}

  l_arm_wr_r_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_wr_r
    pid: {p: 15000.0, i: 0.1, d: 800.0}

  l_arm_wr_y_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_wr_y
    pid: {p: 10000.0, i: 0.1, d: 500.0}

  l_arm_wr_p_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_wr_p
    pid: {p: 7000.0, i: 0.1, d: 400.0}

  l_arm_grip_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_grip
    pid: {p: 7000.0, i: 0.1, d: 300.0}

  l_arm_grip_1_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_grip_1
    pid: {p: 7000.0, i: 0.1, d: 300.0}

  # Right Arm -----

  r_arm_sh_p1_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_sh_p1
    pid: {p: 15000.0, i: 0.1, d: 1000.0}

  r_arm_sh_r_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_sh_r
    pid: {p: 15000.0, i: 0.1, d: 800.0}

  r_arm_sh_p2_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_sh_p2
    pid: {p: 15000.0, i: 0.1, d: 800.0}

  r_arm_el_y_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_el_y
    pid: {p: 15000.0, i: 0.1, d: 800.0}

  r_arm_wr_r_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_wr_r
    pid: {p: 15000.0, i: 0.1, d: 800.0}

  r_arm_wr_y_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_wr_y
    pid: {p: 10000.0, i: 0.1, d: 500.0}

  r_arm_wr_p_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_wr_p
    pid: {p: 7000.0, i: 0.1, d: 400.0}

  r_arm_grip_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_grip
    pid: {p: 7000.0, i: 0.1, d: 300.0}

  r_arm_grip_1_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_grip_1
    pid: {p: 7000.0, i: 0.1, d: 300.0}

  # Left Leg -----

  l_leg_hip_y_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_hip_y
    pid: {p: 8000.0, i: 0.1, d: 500.0}

  l_leg_hip_r_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_hip_r
    pid: {p: 10000.0, i: 0.1, d: 500.0}

  l_leg_hip_p_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_hip_p
    pid: {p: 8000.0, i: 0.1, d: 500.0}

  l_leg_kn_p_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_kn_p
    pid: {p: 10000.0, i: 0.1, d: 500.0}

  l_leg_an_p_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_an_p
    pid: {p: 8000.0, i: 0.1, d: 400.0}

  l_leg_an_r_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_an_r
    pid: {p: 10000.0, i: 0.1, d: 400.0}

  # Right Leg -----

  r_leg_hip_y_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_hip_y
    pid: {p: 8000.0, i: 0.1, d: 500.0}

  r_leg_hip_r_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_hip_r
    pid: {p: 10000.0, i: 0.1, d: 500.0}

  r_leg_hip_p_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_hip_p
    pid: {p: 8000.0, i: 0.1, d: 500.0}

  r_leg_kn_p_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_kn_p
    pid: {p: 10000.0, i: 0.1, d: 500.0}

  r_leg_an_p_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_an_p
    pid: {p: 8000.0, i: 0.1, d: 400.0}

  r_leg_an_r_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_an_r
    pid: {p: 10000.0, i: 0.1, d: 400.0}

  # Head -----

  head_y_position:
    type: effort_controllers/JointPositionController
    joint: head_y
    pid: {p: 1000.0, i: 0.1, d: 80.0}

  head_p_position:
    type: effort_controllers/JointPositionController
    joint: head_p
    pid: {p: 500.0, i: 0.1, d: 40.0}
